title: Nalita Kusnandar
#logo: /assets/img/headshot_circle.png
description: 
Hi, my name is Nalita!

I am a Computer Science fresh graduate specialising in Data Science and Artificial Intelligence. 
Previously, I was a Cloud Engineer Trainee at Cloud Kinetics here in Kuala Lumpur. In this role, I focused on gaining experience in AWS services by conducting a lift & shift migration of a customer's on-premise server to AWS Cloud, mapping 600+ servers to Amazon EC2 instances, and delivering in-depth tutorials into the AWS Systems Manager and Amazon CloudWatch services to upskill stakeholders in AWS proficiency. I also achieved a 97% score on the AWS Certified Cloud Practitioner exam at this time. 
The projects I am proud to share with you are Data Science related, in which I formed business questions, preprocessed data, conducted exploratory data analysis, and leveraged machine learning algorithms to make meaningful predictions. As an aspiring data scientist, I have also done presentations on my work to technical and non-technical audiences using impactful visualisations. 
With my passion for leveraging the power of data and AI in contributing to the growth of Southeast Asia, I am eager to join a leading tech company to drive innovation and make a meaningful impact. 
Don't hesitate to contact me at nalitafairuz@gmail.com. Let's chat!
show_downloads: False
theme: jekyll-theme-minimal
